export const siteConfig = {
  name: 'One Films Ubatuba - Produções Audiovisuais',
  description:
    'Produções audiovisuais totalmente personalizados, projetados para atingir seus objetivos',
  generator: 'Next.js',
  keywords: [
    'One Films Ubatuba',
    'Produções Audiovisuais',
    'produtora audiovisual',
    'Vídeos',
    'Storytelling Persuasivo',
    'Storytelling',
    'Locução',
    'Locução profissional',
    'Locução para vídeos',
    'Locução para vídeos institucionais',
    'Vídeos Estratégicos para Redes Sociais',
    'Vídeos Estratégicos',
    'Vídeos para Redes Sociais',
    'Vídeos para Instagram',
    'Vídeos para Facebook',
    'Vídeos para YouTube',
    'Marketing',
    'Marketing digital',
    'Marketing de conteúdo',
    'Tráfego pago',
    'Tráfego orgânico',
    'SEO',
    'Google Ads',
    'Facebook Ads',
    'Instagram Ads',
    'YouTube Ads',
    'Desenvolvimento de sites',
    'Desenvolvimento de aplicativos web',
    'Ubatuba',
    'Litoral Norte',
    'Comunicação audiovisual',
    'Comunicação',
    'São Paulo',
    'Audiovisual e fotografia',
    'Audiovisual',
    'Fotografia',
    'Vídeos institucionais',
    'Vídeos promocionais',
    'Vídeos publicitários',
    'Vídeos de treinamento',
    'Vídeos de eventos',
    'Vídeos de produtos',
    'Vídeos de serviços',
    'Vídeos de lançamentos',
  ],
  category: 'Marketing',
  mainNav: [
    {
      title: 'Quem somos',
      href: '#quem-somos',
    },
    {
      title: 'Serviços e portfólio',
      href: '#serviços-e-portfólio',
    },
    {
      title: 'Contato',
      href: '#contato',
    },
  ],
  links: {
    instagram: 'https://github.com/nextui-org/nextui',
    whatsApp: 'https://twitter.com/getnextui',
  },
  contact: {
    phone: '+55 (11) 99999-9999',
    whatssApp: '+55 (11) 99999-9999',
  },
  address: {
    street: 'Rua da Alegria, 123',
    city: 'São Paulo',
    state: 'SP',
    zip: '01234-567',
  },
  authors: [
    { name: 'Tomás Lillo' },
    { name: 'Tomás', url: 'https://www.linkedin.com/in/tomasbenjamin/' },
  ],
}

export type SiteConfig = typeof siteConfig
